### ISSUE TITLE
Run on system start?

### ISSUE THREAD

**Issue by LudwikJaniuk** [babin101/DevKeyboard#10]
So, is there an option to start devKeyboard on system start or do I have to launch it myself?

**Comment by benwoodman** [comment]
@LudwikJaniuk Yes, would you like me to add that? I just figured people would get mad if I added that feature.

**Comment by LudwikJaniuk** [comment]
Mad? This is, like, mandatory! 
(As long as it can be toggled off in the settings, of course)

**Comment by LudwikJaniuk** [comment]
(In other words, yes, I'd love that feature!)

**Comment by benwoodman** [comment]
@LudwikJaniuk Okay, I'll work on this.

**Comment by vu5** [comment]
Give an option to the user; a tick box where a user can choose whether to
load it automatically or not.

**Comment by ashlemash** [comment]
@LudwikJaniuk There's a folder called `Start Menu\Programs\Startup` you might want to research...

(`Win+R` > `shell:startup`)

**Comment by benwoodman** [comment]
@daemonaka Yeah, I'm going to make DevKeyboard so it creates a shortcut in that folder to launch itself on startup.

**Comment by LudwikJaniuk** [comment]
@daemonaka Oh, sure, I know about that one, but I think you'll agree it's customary of programs to do that themselves and not expect every user to put a shortcut there.

**Comment by benwoodman** [comment]
I added this feature in the new 1.4 release. Head into the settings page, and check the AutoRun box. Thanks for the suggestion
