### ISSUE TITLE
Check devKeyboard status (Sounds)

### ISSUE THREAD

**Issue by LudwikJaniuk** [babin101/DevKeyboard#11]
Okay, so we can toggle it with `Super-J`. However, (and I know this is a small detail), I'd love a way to check it it's currently on or off without having to try or opening the tray (both operations are time consuming). Some ideas include:
- Play an "on" or "off" sound when enabling/disabling 
- Or display an animation if possible
- Or make the icon visible in the task bar on the bottom when toggling
- Or have a new key binding that just shows the current staus in some way (sound/animation/display in task bar)

As said, this is minor, but it would be nice either way.

**Comment by LudwikJaniuk** [comment]
And maybe I should mention that the icon in the task bar goes away a time after launching the program for me, it hides in the tray. This is maybe different for other people. It also makes it so I can't see the icon to check whether it's on or off.

**Comment by vu5** [comment]
Program icon is hidden by Windows, however, you an just [drag it and place
it in a visible spot and it will stay there](http://www.howtogeek.com/75510/beginner-how-to-customize-and-tweak-your-system-tray-icons-in-windows-7/)

**Comment by vu5** [comment]
A good option would be to colour code the icon. By glancing at the system tray we can see which mode we are really in.

PS: why is my link broken? it is working in preview but not when updated

**Comment by LudwikJaniuk** [comment]
The icon _is_ color coded, I didn't know you could unhide it tho, so thanks! However, we'll see what the creator will think about the sounds, I still think they might be something.

**Comment by benwoodman** [comment]
@LudwikJaniuk @vu5 I'll definitely see if I can add sounds for the next update.

**Comment by benwoodman** [comment]
I have added this feature in the new 1.4 release. Thank you for suggesting this
