### ISSUE TITLE
If d key is not mappedk, DevKeyboard changes "d" to "dk" immediately

### ISSUE THREAD

**Issue by TamaMcGlinn** [babin101/DevKeyboard#13]
Great projdkect, but unfortunately not useable for me dkue to an error. When I tap the "d" key, it changes it to dk immedkiately (not holdking in the button, it is not dependent on the time you set either). I've triedk changing my settings and found a workaround; if you map anything at all to the d key, the error goes away.
Attachedk are my settings.

![devkeyboard](https://cloud.githubusercontent.com/assets/5008897/8376169/68aee588-1c04-11e5-8392-0d2da416fa0b.PNG)

**Comment by benwoodman** [comment]
Okay. I'm really sorry about this. I'll look into it immediately.

**Comment by benwoodman** [comment]
@TamaHobbit I have published a new [prerelease (1.3.1)](https://github.com/babin101/DevKeyboard/releases) that should solve this problem. Please try it out, and if all goes well, I will make it a stable release in the next few days.

**Comment by benwoodman** [comment]
@TamaHobbit Okay, this bug is now fixed as part of the latest release. Check it out now (v1.3.1).
