### ISSUE TITLE
Update assumes incorrect directory

### ISSUE THREAD

**Issue by TamaMcGlinn** [babin101/DevKeyboard#14]
I got a popup asking whether I wanted to update to 1.3.1, to which I clicked okay (I tested it at home and it fixes my 'd' key issue - thanks a lot for the fast update!). It installed to C:\Progra... etc. but my original installation was on E:. This resulted in two installations of devkeyboard (I've removed both and reinstalled now)

If you want to have an update facility you should probably store the install dir in a registry key or something. However, I think automatic updates aren't really necessary for a program like this so it's probably good enough to just remove/disable it.

**Comment by benwoodman** [comment]
Did you specify the installation to be on the E drive last time? @TamaHobbit

**Comment by TamaMcGlinn** [comment]
Yes, originally I installed DevKeyboard to E:\Program Files\DevKeyboard (i.e. I replaced C -> E when the installer asked where to put it).

**Comment by benwoodman** [comment]
Honestly, I don't have a fix for this right now. I'll see what I can do, but I also don't know if I even can fix it.

**Comment by TamaMcGlinn** [comment]
Hmmm, but the 1.4 update worked fine, and installed to E correctly. Either
it fixed itself, or I was somehow mistaken during the first update; either
way, you can mark this fixed.

**Comment by benwoodman** [comment]
All right, well thanks for bringing this to my attention, I'll keep trying to replicate the problem and see if I can create some more consistency.
