### ISSUE TITLE
d -> dk now appears as j -> jd and f -> fjd

### ISSUE THREAD

**Issue by TamaMcGlinn** [babin101/DevKeyboard#15]
So, same bug, different key. jd whenever I press jdust the 'j' key. I now have all keys unbound.

the quick brown fjdox jdumps over the lazy dog.

**Comment by benwoodman** [comment]
Okay, I will work on this right away. Thank you for alerting me of this. So sorry it's taken so long for me to get back to you!

**Comment by TamaMcGlinn** [comment]
No need to be sorry - you're making software for us all for free, after all ! Thanks and keep up the good work.

It is strange that it affects only specific keys - but you might easily solve it using my current workaround; when the assignment should be empty, I in fact put in the key itself, so that j maps to j etc.
(but yes, it would be better to find the source of the problem than to add an extra level of indirection)

**Comment by benwoodman** [comment]
This is now patched in the latest 1.4 release. Go ahead and download it now.
