### ISSUE TITLE
Always starts in small caps

### ISSUE THREAD

**Issue by LudwikJaniuk** [babin101/DevKeyboard#21]
If you enable DK with upper caps, it will behave as if it was on lower (giving lowercase letters). Luckily when you press caps again it does get to the correct state (so, still lowercase), and then if you use caps lock again everything works properly. Nevertheless, a check-caps-on-enable would be a good thing.

**Comment by LudwikJaniuk** [comment]
(Also, upon further testing I noticed that if you: 
1. switch DK on 
2. Change Caps to Upper 
3. Switch DK off
4. Caps to lower
5. DK on

...it still writes in upper. So, again, a check-caps-on-enable would be a good thing!)

**Comment by benwoodman** [comment]
Okay, thanks I'll work on it.

**Comment by benwoodman** [comment]
All right, I think it's fixed. Go ahead and try it out

**Comment by LudwikJaniuk** [comment]
Flexin' my tester muscles...

**Comment by benwoodman** [comment]
Lol, thanks as always

**Comment by LudwikJaniuk** [comment]
Yep, seems fixed to me!

**Comment by benwoodman** [comment]
@LudwikJaniuk by the way, I made a new release - 1.5 beta. You can check it out if you want.

**Comment by LudwikJaniuk** [comment]
You mean with the new sounds? I've gotten it. The're still too loud if you ask me, but sure better than before. And great idea to have separate on/off sounds!

Also, I personally don't like the "Devkeyboard is now on" etc. notifications. They just get annoying in the long run, a switch for them in the settings would be nice.

**Comment by benwoodman** [comment]
I don't really want to clutter the settings. Do you think I should just delete the notification part? I can also make the sounds quieter if needed.

**Comment by LudwikJaniuk** [comment]
I recognize that they serve a purpose, if someone just installed DK he may be surprised by what is happening if he accidentally flicks Super + J or something, so I don't think you should get rid of them completely. But having that thing pop up all the time during the day as you constantly switch DK on/off isn't good either. 

Personally, I'd see nothing wrong with more stuff in the settings (I could think of a few more switches to put there) but if you like to keep them clean - how about an .ini file, "for advanced users"? ;)

Otherwise, you could perhaps make them disappear after a few switches.

**Comment by benwoodman** [comment]
I honestly still don't understand how ini files are different from txt files

**Comment by LudwikJaniuk** [comment]
It's a (very simple) syntax for storing multiple "variables" in one file. Read about it on Wikipedia. As an example, instead of your approach of having A.txt, B.txt, C.txt and so on, you could have e.g. "Keymap.txt":

```
G = <
F = {
D = (
sounds_on = true
notifications_on = false
; This is a comment. Hey, isn't this the same syntax as AHK?
```

That's all there is to it_. So you see, they *are_ text files, just with some simple syntax. The `.ini` extension is just a convention so that another person (or a program) knows it's an INI file.
Now, most languages have tons if INI-parser libraries because it's trivial to implement one, however, I do not know if that's the case with AHK.

*There's more, but you don't have to use it. Read on wikipedia.
