### ISSUE TITLE
This interferes with games, applications...

### ISSUE THREAD

**Issue by LudwikJaniuk** [babin101/DevKeyboard#5]
I'm not even sure it can be fixed, save maybe by adding a blacklist/whitelist for programs it should go with... but if any application uses the letters as key bindings, there are problems. Games with WASD layout? Won't work. Chrome reacts to backspace key by going back one page; now this happens whenever I hold "g" a!bit too long. OR any other of the keys. 

WhatI'm saying is, this program is great when writing code, but something must be done so it won't interfere with work otherwise.

**Comment by githuis** [comment]
You should probably disable it when playing games. As it's made for programming, not gaming.

**Comment by benwoodman** [comment]
Oh, I forgot to add this in the README, I'm doing it right now. If you hold the start button and press J, it will disable the hotkeys. If you press them again, it re enables them.

**Comment by LudwikJaniuk** [comment]
Well that's perfect then! I'm closing the issue.
