### ISSUE TITLE
More buttons

### ISSUE THREAD

**Issue by LudwikJaniuk** [babin101/DevKeyboard#8]
Is there a reason why only so few buttons are added? I'm assuming it's because they are the center ones, but I'd say add a few more - a bit of the third row at least.

**Comment by benwoodman** [comment]
I'm going to work on this in the future.

**Comment by benwoodman** [comment]
@LudwikJaniuk I have pushed a new update - v1.3 - which now allows you to change the shortcut of any of the letter keys. Either restart DevKeyboard and follow the auto-update instructions, or go to my releases page and download version 1.3. This adds support for these new keys: q, w, e, r, t, y, u, i, o, p

**Comment by LudwikJaniuk** [comment]
And perfect! I'm clossing the issue.
