### ISSUE TITLE
Better settings page

### ISSUE THREAD

**Issue by LudwikJaniuk** [babin101/DevKeyboard#9]
Right now, the settings page is really ugly and hard to use. I'd propose (tho there are surely many ways to make it better) a grid-based layout, something like a table. Here is a drawing:
![devkeyboard](https://cloud.githubusercontent.com/assets/6298393/8101295/e8219c98-1015-11e5-908d-b015c5a39ad3.png)

Tho by all means you can make it a different layout if you want.

**Comment by benwoodman** [comment]
That's a great idea! I'll work on that for the next update.

**Comment by benwoodman** [comment]
I'm adding the help wanted tag to this issue, because it seems that this is much harder to incorporate than I originally thought.

**Comment by LudwikJaniuk** [comment]
I'll clone it and see if I can help you out

**Comment by LudwikJaniuk** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6298393/8892976/50bdddc0-337a-11e5-9620-e490466716df.jpg)
Here's a first iteration of improvements, but I've got more coming.

**Comment by benwoodman** [comment]
Wow that looks great. I'd love to see how you were able to do that.

**Comment by LudwikJaniuk** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6298393/8893659/ddf59c54-3399-11e5-8a56-079c5ec9f461.jpg)
Ok, here's the final product. I'm going to try to submit a pull request now, but I think I messed something up with git (cloned instead of forking, and now I have commited to my local version of your repo, but don't have access to publish the changes...) so it may take a while to figure that out.

**Comment by benwoodman** [comment]
I added this in the new 1.4 update. Thank you so much for helping out!
